[package]
name = "fasthash"
version = "0.4.0"
authors = ["Flier Lu <flier.lu@gmail.com>"]
description = "A suite of non-cryptographic hash functions for Rust."
homepage = "https://github.com/flier/rust-fasthash"
repository = "https://github.com/flier/rust-fasthash.git"
documentation = "https://flier.github.io/rust-fasthash/"
keywords = ["hash", "hashing"]
license = "Apache-2.0"

[features]
default = ["sse42", "aes", "avx", "avx2", "doc"]
doc = []
sse42 = ["fasthash-sys/sse42"]
aes = ["fasthash-sys/aes"]
avx = ["fasthash-sys/avx"]
avx2 = ["fasthash-sys/avx2"]
gen = ["fasthash-sys/gen"]

[dependencies]
cfg-if = "0.1"
num-traits = "0.2"
xoroshiro128 = "0.3"
seahash = "3.0"
fasthash-sys = { version = "0.3.2", path = "../fasthash-sys", default-features = false }

[dev-dependencies]
lazy_static = "1.3"
criterion = "0.2"

[[bench]]
name = "hash"
harness = false
